# Desarrollo local sin autenticación
local_backend: true

# Configuración de backend para uso local
backend:
  name: git-gateway
  branch: main

# Rutas de medios
media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: true}
      - {label: "Imagen de Portada", name: "thumbnail", widget: "image"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Categoría", name: "category", widget: "select", options: ["Backend", "Frontend", "DevOps", "Dev Tools", "Otros"]}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Etiquetas", name: "tags", widget: "list"}