backend:
  name: git-gateway
  branch: main
  repo: karkori/portfolio-nextjs
  site_id: 617b4b43-f58c-490f-9009-fb394d95c762

# Para desarrollo local sin necesidad de Netlify
local_backend: true

# Rutas de medios
media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: true}
      - {label: "Imagen de Portada", name: "thumbnail", widget: "image"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Categoría", name: "category", widget: "select", options: ["Desarrollo Web", "JavaScript", "React", "Next.js", "Diseño", "Otros"]}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Etiquetas", name: "tags", widget: "list"}